name: Node App CI/CD

on:
  workflow_dispatch:   # ✅ Manual run option
    inputs:
      environment:
        description: "Choose environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          IMAGE_TAG=$BRANCH_NAME-${{ github.sha }}
          REPO_URI=844605843941.dkr.ecr.ap-south-1.amazonaws.com/node-test-app
          docker build -t $REPO_URI:$IMAGE_TAG .
          docker push $REPO_URI:$IMAGE_TAG
          echo "Image pushed: $REPO_URI:$IMAGE_TAG"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/dev' || github.event.inputs.environment == 'dev'
    steps:
      - name: Deploy to Dev
        run: echo "🚀 Deploying to Dev environment..."

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/qa' || github.event.inputs.environment == 'qa'
    steps:
      - name: Deploy to QA
        run: echo "🚀 Deploying to QA environment..."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'prod'
    environment: prod   # 👈 Needs approval (set in GitHub Environments)
    steps:
      - name: Deploy to Prod
        run: echo "🚀 Deploying to Production..."
